# Generated by Django 5.1.3 on 2025-01-08 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MindMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('vx', models.FloatField(blank=True, null=True)),
                ('vy', models.FloatField(blank=True, null=True)),
                ('index', models.IntegerField(blank=True, null=True)),
                ('mindmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='MindMap.mindmap')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mindmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='MindMap.mindmap')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_from', to='MindMap.node')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_to', to='MindMap.node')),
            ],
        ),
    ]
